// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ssl_visualizer.proto

#ifndef PROTOBUF_ssl_5fvisualizer_2eproto__INCLUDED
#define PROTOBUF_ssl_5fvisualizer_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
#include "ssl_world.pb.h"
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_ssl_5fvisualizer_2eproto();
void protobuf_AssignDesc_ssl_5fvisualizer_2eproto();
void protobuf_ShutdownFile_ssl_5fvisualizer_2eproto();

class ssl_visualizer_packet;

// ===================================================================

class ssl_visualizer_packet : public ::google::protobuf::Message {
 public:
  ssl_visualizer_packet();
  virtual ~ssl_visualizer_packet();
  
  ssl_visualizer_packet(const ssl_visualizer_packet& from);
  
  inline ssl_visualizer_packet& operator=(const ssl_visualizer_packet& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const ssl_visualizer_packet& default_instance();
  
  void Swap(ssl_visualizer_packet* other);
  
  // implements Message ----------------------------------------------
  
  ssl_visualizer_packet* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ssl_visualizer_packet& from);
  void MergeFrom(const ssl_visualizer_packet& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required .ssl_world world = 1;
  inline bool has_world() const;
  inline void clear_world();
  static const int kWorldFieldNumber = 1;
  inline const ::ssl_world& world() const;
  inline ::ssl_world* mutable_world();
  inline ::ssl_world* release_world();
  
  // @@protoc_insertion_point(class_scope:ssl_visualizer_packet)
 private:
  inline void set_has_world();
  inline void clear_has_world();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::ssl_world* world_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_ssl_5fvisualizer_2eproto();
  friend void protobuf_AssignDesc_ssl_5fvisualizer_2eproto();
  friend void protobuf_ShutdownFile_ssl_5fvisualizer_2eproto();
  
  void InitAsDefaultInstance();
  static ssl_visualizer_packet* default_instance_;
};
// ===================================================================


// ===================================================================

// ssl_visualizer_packet

// required .ssl_world world = 1;
inline bool ssl_visualizer_packet::has_world() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ssl_visualizer_packet::set_has_world() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ssl_visualizer_packet::clear_has_world() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ssl_visualizer_packet::clear_world() {
  if (world_ != NULL) world_->::ssl_world::Clear();
  clear_has_world();
}
inline const ::ssl_world& ssl_visualizer_packet::world() const {
  return world_ != NULL ? *world_ : *default_instance_->world_;
}
inline ::ssl_world* ssl_visualizer_packet::mutable_world() {
  set_has_world();
  if (world_ == NULL) world_ = new ::ssl_world;
  return world_;
}
inline ::ssl_world* ssl_visualizer_packet::release_world() {
  clear_has_world();
  ::ssl_world* temp = world_;
  world_ = NULL;
  return temp;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ssl_5fvisualizer_2eproto__INCLUDED
