// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ssl_analyzer.proto

#ifndef PROTOBUF_ssl_5fanalyzer_2eproto__INCLUDED
#define PROTOBUF_ssl_5fanalyzer_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_ssl_5fanalyzer_2eproto();
void protobuf_AssignDesc_ssl_5fanalyzer_2eproto();
void protobuf_ShutdownFile_ssl_5fanalyzer_2eproto();

class ssl_analyzer_packet;

// ===================================================================

class ssl_analyzer_packet : public ::google::protobuf::Message {
 public:
  ssl_analyzer_packet();
  virtual ~ssl_analyzer_packet();
  
  ssl_analyzer_packet(const ssl_analyzer_packet& from);
  
  inline ssl_analyzer_packet& operator=(const ssl_analyzer_packet& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const ssl_analyzer_packet& default_instance();
  
  void Swap(ssl_analyzer_packet* other);
  
  // implements Message ----------------------------------------------
  
  ssl_analyzer_packet* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ssl_analyzer_packet& from);
  void MergeFrom(const ssl_analyzer_packet& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required uint32 nearest_blue_id = 1;
  inline bool has_nearest_blue_id() const;
  inline void clear_nearest_blue_id();
  static const int kNearestBlueIdFieldNumber = 1;
  inline ::google::protobuf::uint32 nearest_blue_id() const;
  inline void set_nearest_blue_id(::google::protobuf::uint32 value);
  
  // required uint32 nearest_yellow_id = 2;
  inline bool has_nearest_yellow_id() const;
  inline void clear_nearest_yellow_id();
  static const int kNearestYellowIdFieldNumber = 2;
  inline ::google::protobuf::uint32 nearest_yellow_id() const;
  inline void set_nearest_yellow_id(::google::protobuf::uint32 value);
  
  // repeated double access_time_blue_vec = 3;
  inline int access_time_blue_vec_size() const;
  inline void clear_access_time_blue_vec();
  static const int kAccessTimeBlueVecFieldNumber = 3;
  inline double access_time_blue_vec(int index) const;
  inline void set_access_time_blue_vec(int index, double value);
  inline void add_access_time_blue_vec(double value);
  inline const ::google::protobuf::RepeatedField< double >&
      access_time_blue_vec() const;
  inline ::google::protobuf::RepeatedField< double >*
      mutable_access_time_blue_vec();
  
  // repeated double access_time_yellow_vec = 4;
  inline int access_time_yellow_vec_size() const;
  inline void clear_access_time_yellow_vec();
  static const int kAccessTimeYellowVecFieldNumber = 4;
  inline double access_time_yellow_vec(int index) const;
  inline void set_access_time_yellow_vec(int index, double value);
  inline void add_access_time_yellow_vec(double value);
  inline const ::google::protobuf::RepeatedField< double >&
      access_time_yellow_vec() const;
  inline ::google::protobuf::RepeatedField< double >*
      mutable_access_time_yellow_vec();
  
  // optional string comment = 5;
  inline bool has_comment() const;
  inline void clear_comment();
  static const int kCommentFieldNumber = 5;
  inline const ::std::string& comment() const;
  inline void set_comment(const ::std::string& value);
  inline void set_comment(const char* value);
  inline void set_comment(const char* value, size_t size);
  inline ::std::string* mutable_comment();
  inline ::std::string* release_comment();
  
  // @@protoc_insertion_point(class_scope:ssl_analyzer_packet)
 private:
  inline void set_has_nearest_blue_id();
  inline void clear_has_nearest_blue_id();
  inline void set_has_nearest_yellow_id();
  inline void clear_has_nearest_yellow_id();
  inline void set_has_comment();
  inline void clear_has_comment();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::uint32 nearest_blue_id_;
  ::google::protobuf::uint32 nearest_yellow_id_;
  ::google::protobuf::RepeatedField< double > access_time_blue_vec_;
  ::google::protobuf::RepeatedField< double > access_time_yellow_vec_;
  ::std::string* comment_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(5 + 31) / 32];
  
  friend void  protobuf_AddDesc_ssl_5fanalyzer_2eproto();
  friend void protobuf_AssignDesc_ssl_5fanalyzer_2eproto();
  friend void protobuf_ShutdownFile_ssl_5fanalyzer_2eproto();
  
  void InitAsDefaultInstance();
  static ssl_analyzer_packet* default_instance_;
};
// ===================================================================


// ===================================================================

// ssl_analyzer_packet

// required uint32 nearest_blue_id = 1;
inline bool ssl_analyzer_packet::has_nearest_blue_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ssl_analyzer_packet::set_has_nearest_blue_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ssl_analyzer_packet::clear_has_nearest_blue_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ssl_analyzer_packet::clear_nearest_blue_id() {
  nearest_blue_id_ = 0u;
  clear_has_nearest_blue_id();
}
inline ::google::protobuf::uint32 ssl_analyzer_packet::nearest_blue_id() const {
  return nearest_blue_id_;
}
inline void ssl_analyzer_packet::set_nearest_blue_id(::google::protobuf::uint32 value) {
  set_has_nearest_blue_id();
  nearest_blue_id_ = value;
}

// required uint32 nearest_yellow_id = 2;
inline bool ssl_analyzer_packet::has_nearest_yellow_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ssl_analyzer_packet::set_has_nearest_yellow_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ssl_analyzer_packet::clear_has_nearest_yellow_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ssl_analyzer_packet::clear_nearest_yellow_id() {
  nearest_yellow_id_ = 0u;
  clear_has_nearest_yellow_id();
}
inline ::google::protobuf::uint32 ssl_analyzer_packet::nearest_yellow_id() const {
  return nearest_yellow_id_;
}
inline void ssl_analyzer_packet::set_nearest_yellow_id(::google::protobuf::uint32 value) {
  set_has_nearest_yellow_id();
  nearest_yellow_id_ = value;
}

// repeated double access_time_blue_vec = 3;
inline int ssl_analyzer_packet::access_time_blue_vec_size() const {
  return access_time_blue_vec_.size();
}
inline void ssl_analyzer_packet::clear_access_time_blue_vec() {
  access_time_blue_vec_.Clear();
}
inline double ssl_analyzer_packet::access_time_blue_vec(int index) const {
  return access_time_blue_vec_.Get(index);
}
inline void ssl_analyzer_packet::set_access_time_blue_vec(int index, double value) {
  access_time_blue_vec_.Set(index, value);
}
inline void ssl_analyzer_packet::add_access_time_blue_vec(double value) {
  access_time_blue_vec_.Add(value);
}
inline const ::google::protobuf::RepeatedField< double >&
ssl_analyzer_packet::access_time_blue_vec() const {
  return access_time_blue_vec_;
}
inline ::google::protobuf::RepeatedField< double >*
ssl_analyzer_packet::mutable_access_time_blue_vec() {
  return &access_time_blue_vec_;
}

// repeated double access_time_yellow_vec = 4;
inline int ssl_analyzer_packet::access_time_yellow_vec_size() const {
  return access_time_yellow_vec_.size();
}
inline void ssl_analyzer_packet::clear_access_time_yellow_vec() {
  access_time_yellow_vec_.Clear();
}
inline double ssl_analyzer_packet::access_time_yellow_vec(int index) const {
  return access_time_yellow_vec_.Get(index);
}
inline void ssl_analyzer_packet::set_access_time_yellow_vec(int index, double value) {
  access_time_yellow_vec_.Set(index, value);
}
inline void ssl_analyzer_packet::add_access_time_yellow_vec(double value) {
  access_time_yellow_vec_.Add(value);
}
inline const ::google::protobuf::RepeatedField< double >&
ssl_analyzer_packet::access_time_yellow_vec() const {
  return access_time_yellow_vec_;
}
inline ::google::protobuf::RepeatedField< double >*
ssl_analyzer_packet::mutable_access_time_yellow_vec() {
  return &access_time_yellow_vec_;
}

// optional string comment = 5;
inline bool ssl_analyzer_packet::has_comment() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void ssl_analyzer_packet::set_has_comment() {
  _has_bits_[0] |= 0x00000010u;
}
inline void ssl_analyzer_packet::clear_has_comment() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void ssl_analyzer_packet::clear_comment() {
  if (comment_ != &::google::protobuf::internal::kEmptyString) {
    comment_->clear();
  }
  clear_has_comment();
}
inline const ::std::string& ssl_analyzer_packet::comment() const {
  return *comment_;
}
inline void ssl_analyzer_packet::set_comment(const ::std::string& value) {
  set_has_comment();
  if (comment_ == &::google::protobuf::internal::kEmptyString) {
    comment_ = new ::std::string;
  }
  comment_->assign(value);
}
inline void ssl_analyzer_packet::set_comment(const char* value) {
  set_has_comment();
  if (comment_ == &::google::protobuf::internal::kEmptyString) {
    comment_ = new ::std::string;
  }
  comment_->assign(value);
}
inline void ssl_analyzer_packet::set_comment(const char* value, size_t size) {
  set_has_comment();
  if (comment_ == &::google::protobuf::internal::kEmptyString) {
    comment_ = new ::std::string;
  }
  comment_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* ssl_analyzer_packet::mutable_comment() {
  set_has_comment();
  if (comment_ == &::google::protobuf::internal::kEmptyString) {
    comment_ = new ::std::string;
  }
  return comment_;
}
inline ::std::string* ssl_analyzer_packet::release_comment() {
  clear_has_comment();
  if (comment_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = comment_;
    comment_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ssl_5fanalyzer_2eproto__INCLUDED
