// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "ssl_visualizer.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* ssl_visualizer_packet_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ssl_visualizer_packet_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_ssl_5fvisualizer_2eproto() {
  protobuf_AddDesc_ssl_5fvisualizer_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "ssl_visualizer.proto");
  GOOGLE_CHECK(file != NULL);
  ssl_visualizer_packet_descriptor_ = file->message_type(0);
  static const int ssl_visualizer_packet_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ssl_visualizer_packet, world_),
  };
  ssl_visualizer_packet_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      ssl_visualizer_packet_descriptor_,
      ssl_visualizer_packet::default_instance_,
      ssl_visualizer_packet_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ssl_visualizer_packet, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ssl_visualizer_packet, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(ssl_visualizer_packet));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_ssl_5fvisualizer_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    ssl_visualizer_packet_descriptor_, &ssl_visualizer_packet::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_ssl_5fvisualizer_2eproto() {
  delete ssl_visualizer_packet::default_instance_;
  delete ssl_visualizer_packet_reflection_;
}

void protobuf_AddDesc_ssl_5fvisualizer_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::protobuf_AddDesc_ssl_5fworld_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\024ssl_visualizer.proto\032\017ssl_world.proto\""
    "2\n\025ssl_visualizer_packet\022\031\n\005world\030\001 \002(\0132"
    "\n.ssl_world", 91);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "ssl_visualizer.proto", &protobuf_RegisterTypes);
  ssl_visualizer_packet::default_instance_ = new ssl_visualizer_packet();
  ssl_visualizer_packet::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_ssl_5fvisualizer_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_ssl_5fvisualizer_2eproto {
  StaticDescriptorInitializer_ssl_5fvisualizer_2eproto() {
    protobuf_AddDesc_ssl_5fvisualizer_2eproto();
  }
} static_descriptor_initializer_ssl_5fvisualizer_2eproto_;


// ===================================================================

#ifndef _MSC_VER
const int ssl_visualizer_packet::kWorldFieldNumber;
#endif  // !_MSC_VER

ssl_visualizer_packet::ssl_visualizer_packet()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void ssl_visualizer_packet::InitAsDefaultInstance() {
  world_ = const_cast< ::ssl_world*>(&::ssl_world::default_instance());
}

ssl_visualizer_packet::ssl_visualizer_packet(const ssl_visualizer_packet& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void ssl_visualizer_packet::SharedCtor() {
  _cached_size_ = 0;
  world_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ssl_visualizer_packet::~ssl_visualizer_packet() {
  SharedDtor();
}

void ssl_visualizer_packet::SharedDtor() {
  if (this != default_instance_) {
    delete world_;
  }
}

void ssl_visualizer_packet::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ssl_visualizer_packet::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ssl_visualizer_packet_descriptor_;
}

const ssl_visualizer_packet& ssl_visualizer_packet::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_ssl_5fvisualizer_2eproto();  return *default_instance_;
}

ssl_visualizer_packet* ssl_visualizer_packet::default_instance_ = NULL;

ssl_visualizer_packet* ssl_visualizer_packet::New() const {
  return new ssl_visualizer_packet;
}

void ssl_visualizer_packet::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_world()) {
      if (world_ != NULL) world_->::ssl_world::Clear();
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool ssl_visualizer_packet::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .ssl_world world = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_world()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void ssl_visualizer_packet::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required .ssl_world world = 1;
  if (has_world()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->world(), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* ssl_visualizer_packet::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required .ssl_world world = 1;
  if (has_world()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->world(), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int ssl_visualizer_packet::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required .ssl_world world = 1;
    if (has_world()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->world());
    }
    
  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ssl_visualizer_packet::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const ssl_visualizer_packet* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const ssl_visualizer_packet*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void ssl_visualizer_packet::MergeFrom(const ssl_visualizer_packet& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_world()) {
      mutable_world()->::ssl_world::MergeFrom(from.world());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void ssl_visualizer_packet::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ssl_visualizer_packet::CopyFrom(const ssl_visualizer_packet& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ssl_visualizer_packet::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;
  
  if (has_world()) {
    if (!this->world().IsInitialized()) return false;
  }
  return true;
}

void ssl_visualizer_packet::Swap(ssl_visualizer_packet* other) {
  if (other != this) {
    std::swap(world_, other->world_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata ssl_visualizer_packet::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ssl_visualizer_packet_descriptor_;
  metadata.reflection = ssl_visualizer_packet_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
