#-------------------------------------------------
#
# Project created by QtCreator 2013-09-06T18:59:38
#
#-------------------------------------------------

QT      += core network
greaterThan(QT_MAJOR_VERSION, 4.0): QT += widgets printsupport
greaterThan(QT_MAJOR_VERSION, 4.9): QT += serialport concurrent

#QT       -= gui

LIBS += -lprotobuf -lboost_system -lboost_filesystem -lBox2D -lqcustomplot

DEFINES += _USE_BOX2D_

release: DESTDIR = $$PWD/../../release_cyrus/server_ui
release: MOC_DIR = $$PWD/../../release_cyrus/server_ui/mocs
release: OBJECTS_DIR = $$PWD/../../release_cyrus/server_ui/objs

debug: DESTDIR = $$PWD/../../debug_cyrus/server_ui
debug: MOC_DIR = $$PWD/../../debug_cyrus/server_ui/mocs
debug: OBJECTS_DIR = $$PWD/../../debug_cyrus/server_ui/objs

TARGET = cyrus2015
#CONFIG   += console
#CONFIG   -= app_bundle

INCLUDEPATH += \
            $$PWD \
            /usr/local/include \
            ../TeamManager \
            ../shared \
            ../shared/utility \
            ../shared/proto \
            ../shared/tools \
            ../shared/tools/vartypes/vartypes \
            ../shared/tools/vartypes/vartypes/gui \
            ../shared/tools/vartypes/vartypes/primitives \
            ../shared/tools/vartypes/vartypes/xml


TEMPLATE = app

SOURCES += \
    transmitter/RobotSerialConnection.cpp \
    ai/SSLWorldModel.cpp \
    definition/SSLTeam.cpp \
    definition/SSLRobot.cpp \
    definition/SSLBall.cpp \
    ai/SSLGame.cpp \
    transmitter/RobotCommandPacket.cpp \
    ../shared/tools/serialib/serialib.cpp \
    ../shared/tools/socket/netraw.cpp \
    ../shared/utility/vector3d.cpp \
    ../shared/utility/vector2d.cpp \
    ai/SSLAnalyzer.cpp \
    soccer/sslagent.cpp \
    soccer/sslstrategy.cpp \
    gui/guihandler.cpp \    
    transmitter/grsimsender.cpp \    
    transmitter/commandtransmitter.cpp \
    referee/SSLReferee.cpp \    
    controller/pidcontroller.cpp \    
    soccer/sslstrategymanager.cpp \
    soccer/sslrolemanager.cpp \
    soccer/sslrole.cpp \
    soccer/roles/waitrebound.cpp \
    soccer/roles/waitpass.cpp \
#    soccer/roles/positionrole.cpp \
    soccer/roles/opponentmarker.cpp \
    soccer/roles/goalkeeper.cpp \
    soccer/roles/defender.cpp \
    soccer/roles/blocker.cpp \
    soccer/roles/activerole.cpp \
    ../shared/proto/grsim/cpp/grsim_Replacement.pb.cc \
    ../shared/proto/grsim/cpp/grsim_Packet.pb.cc \
    ../shared/proto/grsim/cpp/grsim_Commands.pb.cc \
    ../shared/proto/referee/cpp/referee.pb.cc \
    ../shared/proto/vision/cpp/messages_robocup_ssl_wrapper.pb.cc \
    ../shared/proto/vision/cpp/messages_robocup_ssl_refbox_log.pb.cc \
    ../shared/proto/vision/cpp/messages_robocup_ssl_geometry.pb.cc \
    ../shared/proto/vision/cpp/messages_robocup_ssl_detection.pb.cc \
    ../shared/proto/visualizer/cpp/ssl_world.pb.cc \
    ../shared/proto/visualizer/cpp/ssl_visualizer.pb.cc \
    ../shared/proto/visualizer/cpp/ssl_planner.pb.cc \
    ../shared/proto/visualizer/cpp/ssl_decision.pb.cc \
    ../shared/proto/visualizer/cpp/ssl_analyzer.pb.cc \
    paramater-manager/parametermanager.cpp \
    paramater-manager/iniparser.cpp \
    vision/alphabetafilter.cpp \
    vision/robocup_ssl_client.cpp \
    vision/sslframe.cpp \
    planner/planning/planningproblem.cpp \
    planner/planning/trajectory.cpp \
    planner/planning/station.cpp \
    planner/planning/goalstate.cpp \
    planner/planning/planningagent.cpp \
    planner/planning/motionplan.cpp \
    planner/planning/obstacle.cpp \
    planner/planning/fieldbound.cpp \
    planner/planning/dynamicobstacle.cpp \
    ../shared/utility/ellipse.cpp \
    ../shared/utility/shape.cpp \
    soccer/sslgamepositions.cpp \
    soccer/sslskill.cpp \
    test/testvisioninput.cpp \
    test/testreferee.cpp \
    ../shared/utility/linesegment.cpp \
    debug-tools/logger.cpp \
    debug-tools/networkplotter.cpp \
    ../shared/proto/plotter/cpp/message_plotter.pb.cc \
    test/testskills.cpp \
    soccer/roles/sidecleaner.cpp \
    ../shared/utility/randomsampling.cpp \
    ../shared/utility/generalmath.cpp \
    planner/planning/sslplanningagent.cpp \
    planner/planning/spatialtree.cpp \
    planner/planning/rectangularfieldbound.cpp \
    ../shared/tools/vartypes/vartypes/VarXML.cpp \
    ../shared/tools/vartypes/vartypes/VarTypesInstance.cpp \
    ../shared/tools/vartypes/vartypes/VarTypesFactory.cpp \
    ../shared/tools/vartypes/vartypes/VarTypesBase.cpp \
    ../shared/tools/vartypes/vartypes/VarTypes.cpp \
    ../shared/tools/vartypes/vartypes/VarNotifier.cpp \
    ../shared/tools/vartypes/vartypes/VarBase64.cpp \
    ../shared/tools/vartypes/vartypes/gui/VarTreeViewOptions.cpp \
    ../shared/tools/vartypes/vartypes/gui/VarTreeView.cpp \
    ../shared/tools/vartypes/vartypes/gui/VarTreeModel.cpp \
    ../shared/tools/vartypes/vartypes/gui/VarItemDelegate.cpp \
    ../shared/tools/vartypes/vartypes/gui/VarItem.cpp \
    ../shared/tools/vartypes/vartypes/primitives/VarVal.cpp \
    ../shared/tools/vartypes/vartypes/primitives/VarType.cpp \
    ../shared/tools/vartypes/vartypes/primitives/VarTrigger.cpp \
    ../shared/tools/vartypes/vartypes/primitives/VarStringVal.cpp \
    ../shared/tools/vartypes/vartypes/primitives/VarStringEnum.cpp \
    ../shared/tools/vartypes/vartypes/primitives/VarString.cpp \
    ../shared/tools/vartypes/vartypes/primitives/VarShortVal.cpp \
    ../shared/tools/vartypes/vartypes/primitives/VarShort.cpp \
    ../shared/tools/vartypes/vartypes/primitives/VarSelection.cpp \
    ../shared/tools/vartypes/vartypes/primitives/VarQWidget.cpp \
    ../shared/tools/vartypes/vartypes/primitives/VarProtoBufferVal.cpp \
    ../shared/tools/vartypes/vartypes/primitives/VarProtoBuffer.cpp \
    ../shared/tools/vartypes/vartypes/primitives/VarList.cpp \
    ../shared/tools/vartypes/vartypes/primitives/VarIntVal.cpp \
    ../shared/tools/vartypes/vartypes/primitives/VarInt.cpp \
    ../shared/tools/vartypes/vartypes/primitives/VarExternal.cpp \
    ../shared/tools/vartypes/vartypes/primitives/VarDoubleVal.cpp \
    ../shared/tools/vartypes/vartypes/primitives/VarDouble.cpp \
    ../shared/tools/vartypes/vartypes/primitives/VarBoolVal.cpp \
    ../shared/tools/vartypes/vartypes/primitives/VarBool.cpp \
    ../shared/tools/vartypes/vartypes/primitives/VarBlob.cpp \
    ../shared/tools/vartypes/vartypes/xml/xmlParser.cpp \
    ../shared/tools/kalman-cpp/kalman.cpp \
    vision/kalmanfilter.cpp \
    vision/robotkalmanfilter.cpp \
    vision/ballfilter.cpp \
    vision/visionfilter.cpp \
    vision/robotclusterfilter.cpp \
    vision/sslvision.cpp \
    vision/robotfilter.cpp \
    ../TeamManager/watchfieldgraphics.cpp \
    ../TeamManager/mainwindow.cpp \
    ../TeamManager/fieldgraphicsview.cpp \
    ../TeamManager/cyrusserverpackethandler.cpp \
    debug-tools/debugclient.cpp \
    main_gui.cpp \
    debug-tools/builtindebug.cpp \
    ../TeamManager/udpsocket.cpp \
    ../TeamManager/plot-manager/scatterplotwidget.cpp \
    ../TeamManager/plot-manager/qcustomplot.cpp \
    ../TeamManager/plot-manager/plotwidget.cpp \
    ../TeamManager/plot-manager/plotmanagerwidget.cpp

HEADERS += \
    transmitter/RobotSerialConnection.h \
    ../shared/tools/serialib/serialib.h \
    ../shared/tools/socket/ippacket.h \
    ../shared/tools/ssllistener.h \
    ../shared/general.h \
    ai/SSLWorldModel.h \
    definition/SSLTeam.h \
    definition/SSLRobot.h \
    definition/SSLObject.h \
    definition/SSLBall.h \
    ai/SSLGame.h \
    transmitter/RobotCommandPacket.h \
    ../shared/utility/vector3d.h \
    ../shared/utility/vector2d.h \
    ../shared/tools/socket/netraw.h \
    ../shared/tools/util.h \
    ai/SSLAnalyzer.h \
    soccer/sslagent.h \
    soccer/sslstrategy.h \
    gui/guihandler.h \
    transmitter/grsimsender.h \
    transmitter/commandtransmitter.h \
    ../shared/utility/generalmath.h \
    referee/SSLReferee.h \
    soccer/sslstrategymanager.h \
    soccer/sslrole.h \
    soccer/sslrolemanager.h \
    soccer/roles/waitrebound.h \
    soccer/roles/waitpass.h \
#    soccer/roles/positionrole.h \
    soccer/roles/opponentmarker.h \
    soccer/roles/goalkeeper.h \
    soccer/roles/defender.h \
    soccer/roles/blocker.h \
    soccer/roles/activerole.h \
    controller/pidcontroller.h \    
    ../shared/proto/grsim/cpp/grsim_Replacement.pb.h \
    ../shared/proto/grsim/cpp/grsim_Packet.pb.h \
    ../shared/proto/grsim/cpp/grsim_Commands.pb.h \
    ../shared/proto/referee/cpp/referee.pb.h \
    ../shared/proto/vision/cpp/messages_robocup_ssl_wrapper.pb.h \
    ../shared/proto/vision/cpp/messages_robocup_ssl_refbox_log.pb.h \
    ../shared/proto/vision/cpp/messages_robocup_ssl_geometry.pb.h \
    ../shared/proto/vision/cpp/messages_robocup_ssl_detection.pb.h \
    ../shared/proto/visualizer/cpp/ssl_world.pb.h \
    ../shared/proto/visualizer/cpp/ssl_visualizer.pb.h \
    ../shared/proto/visualizer/cpp/ssl_planner.pb.h \
    ../shared/proto/visualizer/cpp/ssl_decision.pb.h \
    ../shared/proto/visualizer/cpp/ssl_analyzer.pb.h \
    iniparser/iniparser.h \
    iniparser/parametermanager.h \
    paramater-manager/parametermanager.h \
    paramater-manager/iniparser.h \
    vision/alphabetafilter.h \
    vision/robocup_ssl_client.h \
    ../shared/utility/linesegment.h \
    vision/sslframe.h \
    planner/planning/obstacle.h \
    planner/planning/planningproblem.h \
    planner/planning/fieldbound.h \
    planner/planning/station.h \
    planner/planning/trajectory.h \
    planner/planning/goalstate.h \
    planner/planning/motionplan.h \
    planner/planning/planningagent.h \
    planner/planning/dynamicobstacle.h \
    ../shared/utility/ellipse.h \
    ../shared/utility/shape.h \
    soccer/sslgamepositions.h \
    soccer/sslskill.h \
    test/testvisioninput.h \
    test/testreferee.h \
    test/testmathfunctions.h \
    debug-tools/logger.h \
    debug-tools/networkplotter.h \
    ../shared/proto/plotter/cpp/message_plotter.pb.h \
    test/testskills.h \
    soccer/roles/sidecleaner.h \
    ../shared/utility/randomsampling.h \
    ../shared/utility/util.h \
    planner/planning/sslplanningagent.h \
    planner/planning/spatialvertex.h \
    planner/planning/spatialtree.h \
    planner/planning/rectangularfieldbound.h \
    ../shared/tools/vartypes/vartypes/VarXML.h \
    ../shared/tools/vartypes/vartypes/VarTypesInstance.h \
    ../shared/tools/vartypes/vartypes/VarTypesFactory.h \
    ../shared/tools/vartypes/vartypes/VarTypesBase.h \
    ../shared/tools/vartypes/vartypes/VarTypes.h \
    ../shared/tools/vartypes/vartypes/VarNotifier.h \
    ../shared/tools/vartypes/vartypes/VarBase64.h \
    ../shared/tools/vartypes/vartypes/DllDefines.h \
    ../shared/tools/vartypes/vartypes/gui/VarTreeViewOptions.h \
    ../shared/tools/vartypes/vartypes/gui/VarTreeView.h \
    ../shared/tools/vartypes/vartypes/gui/VarTreeModel.h \
    ../shared/tools/vartypes/vartypes/gui/VarItemDelegate.h \
    ../shared/tools/vartypes/vartypes/gui/VarItem.h \
    ../shared/tools/vartypes/vartypes/primitives/VarVal.h \
    ../shared/tools/vartypes/vartypes/primitives/VarType.h \
    ../shared/tools/vartypes/vartypes/primitives/VarTrigger.h \
    ../shared/tools/vartypes/vartypes/primitives/VarStringVal.h \
    ../shared/tools/vartypes/vartypes/primitives/VarStringEnum.h \
    ../shared/tools/vartypes/vartypes/primitives/VarString.h \
    ../shared/tools/vartypes/vartypes/primitives/VarShortVal.h \
    ../shared/tools/vartypes/vartypes/primitives/VarShort.h \
    ../shared/tools/vartypes/vartypes/primitives/VarSelection.h \
    ../shared/tools/vartypes/vartypes/primitives/VarQWidget.h \
    ../shared/tools/vartypes/vartypes/primitives/VarProtoBufferVal.h \
    ../shared/tools/vartypes/vartypes/primitives/VarProtoBuffer.h \
    ../shared/tools/vartypes/vartypes/primitives/VarList.h \
    ../shared/tools/vartypes/vartypes/primitives/VarIntVal.h \
    ../shared/tools/vartypes/vartypes/primitives/VarInt.h \
    ../shared/tools/vartypes/vartypes/primitives/VarExternal.h \
    ../shared/tools/vartypes/vartypes/primitives/VarDoubleVal.h \
    ../shared/tools/vartypes/vartypes/primitives/VarDouble.h \
    ../shared/tools/vartypes/vartypes/primitives/VarBoolVal.h \
    ../shared/tools/vartypes/vartypes/primitives/VarBool.h \
    ../shared/tools/vartypes/vartypes/primitives/VarBlob.h \
    ../shared/tools/vartypes/vartypes/xml/xmlParser.h \
    ../shared/tools/kalman-cpp/kalman.hpp \
    vision/kalmanfilter.h \
    vision/robotkalmanfilter.h \
    vision/ballfilter.h \
    vision/visionfilter.h \
    vision/robotclusterfilter.h \
    vision/sslvision.h \
    vision/robotfilter.h \
    ../TeamManager/watchfieldgraphics.h \
    ../TeamManager/mainwindow.h \
    ../TeamManager/fieldgraphicsview.h \
    ../TeamManager/cyrusserverpackethandler.h \
    debug-tools/debugclient.h \
    debug-tools/builtindebug.h \
    ../TeamManager/udpsocket.h \
    ../TeamManager/plot-manager/scatterplotwidget.h \
    ../TeamManager/plot-manager/qcustomplot.h \
    ../TeamManager/plot-manager/plotwidget.h \
    ../TeamManager/plot-manager/plotmanagerwidget.h

OTHER_FILES += \            
    ../shared/proto/referee/proto/*.proto \
    ../shared/proto/vision/proto/*.proto \
    ../shared/proto/visualizer/proto/*.proto \
    ../settings/*.json \
    ../TeamManager/icons/oxygen/zoom-select.png \
    ../TeamManager/icons/oxygen/zoom-previous.png \
    ../TeamManager/icons/oxygen/zoom-out.png \
    ../TeamManager/icons/oxygen/zoom-original.png \
    ../TeamManager/icons/oxygen/zoom-next.png \
    ../TeamManager/icons/oxygen/zoom-in.png \
    ../TeamManager/icons/oxygen/zoom-fit-width.png \
    ../TeamManager/icons/oxygen/zoom-fit-height.png \
    ../TeamManager/icons/oxygen/zoom-fit-best.png \
    ../TeamManager/icons/oxygen/zoom-draw.png \
    ../TeamManager/icons/oxygen/zoom-2-to-1.png \
    ../TeamManager/icons/oxygen/zoom-1-to-2.png \
    ../TeamManager/icons/oxygen/x-shape-text.png \
    ../TeamManager/icons/oxygen/x-shape-image.png \
    ../TeamManager/icons/oxygen/x-shape-formula.png \
    ../TeamManager/icons/oxygen/x-shape-connection.png \
    ../TeamManager/icons/oxygen/x-shape-chart.png \
    ../TeamManager/icons/oxygen/window-new.png \
    ../TeamManager/icons/oxygen/window-duplicate.png \
    ../TeamManager/icons/oxygen/window-close.png \
    ../TeamManager/icons/oxygen/view-web-browser-dom-tree.png \
    ../TeamManager/icons/oxygen/view-time-schedule-insert.png \
    ../TeamManager/icons/oxygen/view-time-schedule-edit.png \
    ../TeamManager/icons/oxygen/view-time-schedule-child-insert.png \
    ../TeamManager/icons/oxygen/view-time-schedule-calculus.png \
    ../TeamManager/icons/oxygen/view-time-schedule-baselined-remove.png \
    ../TeamManager/icons/oxygen/view-time-schedule-baselined-add.png \
    ../TeamManager/icons/oxygen/view-time-schedule-baselined.png \
    ../TeamManager/icons/oxygen/view-time-schedule.png \
    ../TeamManager/icons/oxygen/view-task-child-add.png \
    ../TeamManager/icons/oxygen/view-task-child.png \
    ../TeamManager/icons/oxygen/view-task-add.png \
    ../TeamManager/icons/oxygen/view-task.png \
    ../TeamManager/icons/oxygen/view-table-of-contents-rtl.png \
    ../TeamManager/icons/oxygen/view-table-of-contents-ltr.png \
    ../TeamManager/icons/oxygen/view-stock-account.png \
    ../TeamManager/icons/oxygen/view-statistics.png \
    ../TeamManager/icons/oxygen/view-split-top-bottom.png \
    ../TeamManager/icons/oxygen/view-split-left-right.png \
    ../TeamManager/icons/oxygen/view-sort-descending.png \
    ../TeamManager/icons/oxygen/view-sort-ascending.png \
    ../TeamManager/icons/oxygen/view-sidetree.png \
    ../TeamManager/icons/oxygen/view-right-new.png \
    ../TeamManager/icons/oxygen/view-right-close.png \
    ../TeamManager/icons/oxygen/view-restore.png \
    ../TeamManager/icons/oxygen/view-resource-calendar.png \
    ../TeamManager/icons/oxygen/view-refresh.png \
    ../TeamManager/icons/oxygen/view-process-users.png \
    ../TeamManager/icons/oxygen/view-process-system.png \
    ../TeamManager/icons/oxygen/view-process-own.png \
    ../TeamManager/icons/oxygen/view-process-all-tree.png \
    ../TeamManager/icons/oxygen/view-process-all.png \
    ../TeamManager/icons/oxygen/view-preview.png \
    ../TeamManager/icons/oxygen/view-presentation.png \
    ../TeamManager/icons/oxygen/view-pim-tasks-pending.png \
    ../TeamManager/icons/oxygen/view-pim-tasks.png \
    ../TeamManager/icons/oxygen/view-pim-summary.png \
    ../TeamManager/icons/oxygen/view-pim-notes.png \
    ../TeamManager/icons/oxygen/view-pim-news.png \
    ../TeamManager/icons/oxygen/view-pim-mail.png \
    ../TeamManager/icons/oxygen/view-pim-journal.png \
    ../TeamManager/icons/oxygen/view-pim-contacts.png \
    ../TeamManager/icons/oxygen/view-pim-calendar.png \
    ../TeamManager/icons/oxygen/view-object-histogram-logarithmic.png \
    ../TeamManager/icons/oxygen/view-object-histogram-linear.png \
    ../TeamManager/icons/oxygen/view-multiple-objects.png \
    ../TeamManager/icons/oxygen/view-media-visualization.png \
    ../TeamManager/icons/oxygen/view-media-playlist.png \
    ../TeamManager/icons/oxygen/view-media-lyrics.png \
    ../TeamManager/icons/oxygen/view-media-equalizer.png \
    ../TeamManager/icons/oxygen/view-media-artist.png \
    ../TeamManager/icons/oxygen/view-loan-asset.png \
    ../TeamManager/icons/oxygen/view-loan.png \
    ../TeamManager/icons/oxygen/view-list-tree.png \
    ../TeamManager/icons/oxygen/view-list-text.png \
    ../TeamManager/icons/oxygen/view-list-icons.png \
    ../TeamManager/icons/oxygen/view-list-details.png \
    ../TeamManager/icons/oxygen/view-left-close.png \
    ../TeamManager/icons/oxygen/view-ldap-resource.png \
    ../TeamManager/icons/oxygen/view-investment.png \
    ../TeamManager/icons/oxygen/view-income-categories.png \
    ../TeamManager/icons/oxygen/view-history.png \
    ../TeamManager/icons/oxygen/view-group.png \
    ../TeamManager/icons/oxygen/view-grid.png \
    ../TeamManager/icons/oxygen/view-fullscreen.png \
    ../TeamManager/icons/oxygen/view-form-table.png \
    ../TeamManager/icons/oxygen/view-form-action.png \
    ../TeamManager/icons/oxygen/view-form.png \
    ../TeamManager/icons/oxygen/view-financial-transfer.png \
    ../TeamManager/icons/oxygen/view-financial-payment-mode.png \
    ../TeamManager/icons/oxygen/view-financial-list.png \
    ../TeamManager/icons/oxygen/view-financial-forecast.png \
    ../TeamManager/icons/oxygen/view-financial-categories.png \
    ../TeamManager/icons/oxygen/view-filter.png \
    ../TeamManager/icons/oxygen/view-file-columns.png \
    ../TeamManager/icons/oxygen/view-expenses-categories.png \
    ../TeamManager/icons/oxygen/view-documents-finances.png \
    ../TeamManager/icons/oxygen/view-currency-list.png \
    ../TeamManager/icons/oxygen/view-credit-card-account.png \
    ../TeamManager/icons/oxygen/view-conversation-balloon.png \
    ../TeamManager/icons/oxygen/view-close.png \
    ../TeamManager/icons/oxygen/view-choose.png \
    ../TeamManager/icons/oxygen/view-certificate-sign.png \
    ../TeamManager/icons/oxygen/view-certificate-server-configure.png \
    ../TeamManager/icons/oxygen/view-certificate-import.png \
    ../TeamManager/icons/oxygen/view-certificate-export-server.png \
    ../TeamManager/icons/oxygen/view-certificate-export-secret.png \
    ../TeamManager/icons/oxygen/view-certificate-export.png \
    ../TeamManager/icons/oxygen/view-certificate-add.png \
    ../TeamManager/icons/oxygen/view-certificate.png \
    ../TeamManager/icons/oxygen/view-categories.png \
    ../TeamManager/icons/oxygen/view-catalog.png \
    ../TeamManager/icons/oxygen/view-calendar-workweek.png \
    ../TeamManager/icons/oxygen/view-calendar-whatsnext.png \
    ../TeamManager/icons/oxygen/view-calendar-week.png \
    ../TeamManager/icons/oxygen/view-calendar-wedding-anniversary.png \
    ../TeamManager/icons/oxygen/view-calendar-upcoming-events.png \
    ../TeamManager/icons/oxygen/view-calendar-upcoming-days.png \
    ../TeamManager/icons/oxygen/view-calendar-time-spent.png \
    ../TeamManager/icons/oxygen/view-calendar-timeline.png \
    ../TeamManager/icons/oxygen/view-calendar-tasks.png \
    ../TeamManager/icons/oxygen/view-calendar-special-occasion.png \
    ../TeamManager/icons/oxygen/view-calendar-month.png \
    ../TeamManager/icons/oxygen/view-calendar-list.png \
    ../TeamManager/icons/oxygen/view-calendar-journal.png \
    ../TeamManager/icons/oxygen/view-calendar-holiday.png \
    ../TeamManager/icons/oxygen/view-calendar-day.png \
    ../TeamManager/icons/oxygen/view-calendar-birthday.png \
    ../TeamManager/icons/oxygen/view-calendar-agenda.png \
    ../TeamManager/icons/oxygen/view-calendar.png \
    ../TeamManager/icons/oxygen/view-barcode-add.png \
    ../TeamManager/icons/oxygen/view-barcode.png \
    ../TeamManager/icons/oxygen/view-bank-account-savings.png \
    ../TeamManager/icons/oxygen/view-bank-account-checking.png \
    ../TeamManager/icons/oxygen/view-bank-account.png \
    ../TeamManager/icons/oxygen/view-bank.png \
    ../TeamManager/icons/oxygen/user-properties.png \
    ../TeamManager/icons/oxygen/user-group-properties.png \
    ../TeamManager/icons/oxygen/user-group-new.png \
    ../TeamManager/icons/oxygen/user-group-delete.png \
    ../TeamManager/icons/oxygen/trash-empty.png \
    ../TeamManager/icons/oxygen/transform-shear-up.png \
    ../TeamManager/icons/oxygen/transform-shear-right.png \
    ../TeamManager/icons/oxygen/transform-shear-left.png \
    ../TeamManager/icons/oxygen/transform-shear-down.png \
    ../TeamManager/icons/oxygen/transform-scale-textbox-points.png \
    ../TeamManager/icons/oxygen/transform-scale.png \
    ../TeamManager/icons/oxygen/transform-rotate.png \
    ../TeamManager/icons/oxygen/transform-move.png \
    ../TeamManager/icons/oxygen/transform-crop-and-resize.png \
    ../TeamManager/icons/oxygen/transform-crop.png \
    ../TeamManager/icons/oxygen/tools-wizard.png \
    ../TeamManager/icons/oxygen/tools-rip-video-dvd.png \
    ../TeamManager/icons/oxygen/tools-rip-video-cd.png \
    ../TeamManager/icons/oxygen/tools-rip-audio-cd.png \
    ../TeamManager/icons/oxygen/tools-report-bug.png \
    ../TeamManager/icons/oxygen/tools-media-optical-format.png \
    ../TeamManager/icons/oxygen/tools-media-optical-erase.png \
    ../TeamManager/icons/oxygen/tools-media-optical-copy.png \
    ../TeamManager/icons/oxygen/tools-media-optical-burn-image.png \
    ../TeamManager/icons/oxygen/tools-media-optical-burn.png \
    ../TeamManager/icons/oxygen/tools-check-spelling.png \
    ../TeamManager/icons/oxygen/tool-animator.png \
    ../TeamManager/icons/oxygen/text-speak.png \
    ../TeamManager/icons/oxygen/text-frame-unlink.png \
    ../TeamManager/icons/oxygen/text-frame-link.png \
    ../TeamManager/icons/oxygen/text-field.png \
    ../TeamManager/icons/oxygen/taxes-finances.png \
    ../TeamManager/icons/oxygen/task-new.png \
    ../TeamManager/icons/oxygen/tab-new-background.png \
    ../TeamManager/icons/oxygen/tab-new.png \
    ../TeamManager/icons/oxygen/table.png \
    ../TeamManager/icons/oxygen/tab-duplicate.png \
    ../TeamManager/icons/oxygen/tab-detach.png \
    ../TeamManager/icons/oxygen/tab-close-other.png \
    ../TeamManager/icons/oxygen/tab-close.png \
    ../TeamManager/icons/oxygen/system-switch-user.png \
    ../TeamManager/icons/oxygen/system-suspend-hibernate.png \
    ../TeamManager/icons/oxygen/system-suspend.png \
    ../TeamManager/icons/oxygen/system-shutdown.png \
    ../TeamManager/icons/oxygen/system-search.png \
    ../TeamManager/icons/oxygen/system-run.png \
    ../TeamManager/icons/oxygen/system-reboot.png \
    ../TeamManager/icons/oxygen/system-log-out.png \
    ../TeamManager/icons/oxygen/system-lock-screen.png \
    ../TeamManager/icons/oxygen/svn-update.png \
    ../TeamManager/icons/oxygen/svn-commit.png \
    ../TeamManager/icons/oxygen/stroke-join-round.png \
    ../TeamManager/icons/oxygen/stroke-join-miter.png \
    ../TeamManager/icons/oxygen/stroke-join-bevel.png \
    ../TeamManager/icons/oxygen/stroke-cap-square.png \
    ../TeamManager/icons/oxygen/stroke-cap-round.png \
    ../TeamManager/icons/oxygen/stroke-cap-butt.png \
    ../TeamManager/icons/oxygen/story-editor.png \
    ../TeamManager/icons/oxygen/split.png \
    ../TeamManager/icons/oxygen/speaker.png \
    ../TeamManager/icons/oxygen/snap-orthogonal.png \
    ../TeamManager/icons/oxygen/snap-node.png \
    ../TeamManager/icons/oxygen/snap-intersection.png \
    ../TeamManager/icons/oxygen/snap-guideline.png \
    ../TeamManager/icons/oxygen/snap-extension.png \
    ../TeamManager/icons/oxygen/show-menu.png \
    ../TeamManager/icons/oxygen/shapes.png \
    ../TeamManager/icons/oxygen/shape-choose.png \
    ../TeamManager/icons/oxygen/services.png \
    ../TeamManager/icons/oxygen/select-rectangular.png \
    ../TeamManager/icons/oxygen/run-build.png \
    ../TeamManager/icons/oxygen/roll.png \
    ../TeamManager/icons/oxygen/resource-group-new.png \
    ../TeamManager/icons/oxygen/resource-group.png \
    ../TeamManager/icons/oxygen/resource-calendar-insert.png \
    ../TeamManager/icons/oxygen/resource-calendar-child-insert.png \
    ../TeamManager/icons/oxygen/resource-calendar-child.png \
    ../TeamManager/icons/oxygen/rating.png \
    ../TeamManager/icons/oxygen/quickopen-function.png \
    ../TeamManager/icons/oxygen/quickopen-file.png \
    ../TeamManager/icons/oxygen/quickopen-class.png \
    ../TeamManager/icons/oxygen/quickopen.png \
    ../TeamManager/icons/oxygen/project-open.png \
    ../TeamManager/icons/oxygen/project-development-new-template.png \
    ../TeamManager/icons/oxygen/project-development-close-all.png \
    ../TeamManager/icons/oxygen/project-development-close.png \
    ../TeamManager/icons/oxygen/project-development.png \
    ../TeamManager/icons/oxygen/process-stop.png \
    ../TeamManager/icons/oxygen/preflight-verifier.png \
    ../TeamManager/icons/oxygen/preferences-activities.png \
    ../TeamManager/icons/oxygen/player-volume.png \
    ../TeamManager/icons/oxygen/player-time.png \
    ../TeamManager/icons/oxygen/page-zoom.png \
    ../TeamManager/icons/oxygen/page-simple.png \
    ../TeamManager/icons/oxygen/page-4sides.png \
    ../TeamManager/icons/oxygen/page-3sides.png \
    ../TeamManager/icons/oxygen/page-2sides.png \
    ../TeamManager/icons/oxygen/office-chart-scatter.png \
    ../TeamManager/icons/oxygen/office-chart-ring.png \
    ../TeamManager/icons/oxygen/office-chart-polar-stacked.png \
    ../TeamManager/icons/oxygen/office-chart-polar.png \
    ../TeamManager/icons/oxygen/office-chart-pie.png \
    ../TeamManager/icons/oxygen/office-chart-line-stacked.png \
    ../TeamManager/icons/oxygen/office-chart-line-percentage.png \
    ../TeamManager/icons/oxygen/office-chart-line.png \
    ../TeamManager/icons/oxygen/office-chart-bar-stacked.png \
    ../TeamManager/icons/oxygen/office-chart-bar-percentage.png \
    ../TeamManager/icons/oxygen/office-chart-bar.png \
    ../TeamManager/icons/oxygen/office-chart-area-stacked.png \
    ../TeamManager/icons/oxygen/office-chart-area-percentage.png \
    ../TeamManager/icons/oxygen/office-chart-area-focus-peak-node.png \
    ../TeamManager/icons/oxygen/office-chart-area.png \
    ../TeamManager/icons/oxygen/object-rotate-right.png \
    ../TeamManager/icons/oxygen/object-rotate-left.png \
    ../TeamManager/icons/oxygen/object-flip-vertical.png \
    ../TeamManager/icons/oxygen/object-flip-horizontal.png \
    ../TeamManager/icons/oxygen/news-unsubscribe.png \
    ../TeamManager/icons/oxygen/news-subscribe.png \
    ../TeamManager/icons/oxygen/network-disconnect.png \
    ../TeamManager/icons/oxygen/network-connect.png \
    ../TeamManager/icons/oxygen/milestone.png \
    ../TeamManager/icons/oxygen/merge.png \
    ../TeamManager/icons/oxygen/meeting-participant-request-response.png \
    ../TeamManager/icons/oxygen/meeting-participant-no-response.png \
    ../TeamManager/icons/oxygen/meeting-attending-tentative.png \
    ../TeamManager/icons/oxygen/meeting-attending.png \
    ../TeamManager/icons/oxygen/media-skip-forward.png \
    ../TeamManager/icons/oxygen/media-skip-backward.png \
    ../TeamManager/icons/oxygen/media-seek-forward.png \
    ../TeamManager/icons/oxygen/media-seek-backward.png \
    ../TeamManager/icons/oxygen/media-record.png \
    ../TeamManager/icons/oxygen/media-playback-stop.png \
    ../TeamManager/icons/oxygen/media-playback-start.png \
    ../TeamManager/icons/oxygen/media-playback-pause.png \
    ../TeamManager/icons/oxygen/media-eject.png \
    ../TeamManager/icons/oxygen/measure.png \
    ../TeamManager/icons/oxygen/mail-tagged.png \
    ../TeamManager/icons/oxygen/mail-signed-verified.png \
    ../TeamManager/icons/oxygen/mail-signed-part.png \
    ../TeamManager/icons/oxygen/mail-signed-full.png \
    ../TeamManager/icons/oxygen/mail-signed.png \
    ../TeamManager/icons/oxygen/mail-signature-unknown.png \
    ../TeamManager/icons/oxygen/mail-send.png \
    ../TeamManager/icons/oxygen/mail-reply-sender.png \
    ../TeamManager/icons/oxygen/mail-reply-list.png \
    ../TeamManager/icons/oxygen/mail-reply-custom-all.png \
    ../TeamManager/icons/oxygen/mail-reply-custom.png \
    ../TeamManager/icons/oxygen/mail-reply-all.png \
    ../TeamManager/icons/oxygen/mail-replied.png \
    ../TeamManager/icons/oxygen/mail-receive.png \
    ../TeamManager/icons/oxygen/mail-queue.png \
    ../TeamManager/icons/oxygen/mail-message-new-list.png \
    ../TeamManager/icons/oxygen/mail-message-new.png \
    ../TeamManager/icons/oxygen/mail-meeting-request-reply.png \
    ../TeamManager/icons/oxygen/mail-mark-unread-new.png \
    ../TeamManager/icons/oxygen/mail-mark-unread.png \
    ../TeamManager/icons/oxygen/mail-mark-task.png \
    ../TeamManager/icons/oxygen/mail-mark-read.png \
    ../TeamManager/icons/oxygen/mail-mark-notjunk.png \
    ../TeamManager/icons/oxygen/mail-mark-junk.png \
    ../TeamManager/icons/oxygen/mail-mark-important.png \
    ../TeamManager/icons/oxygen/mail-invitation.png \
    ../TeamManager/icons/oxygen/mail-forwarded.png \
    ../TeamManager/icons/oxygen/mail-forward.png \
    ../TeamManager/icons/oxygen/mail-flag.png \
    ../TeamManager/icons/oxygen/mail-encrypted-part.png \
    ../TeamManager/icons/oxygen/mail-encrypted-full.png \
    ../TeamManager/icons/oxygen/mail-encrypted.png \
    ../TeamManager/icons/oxygen/list-resource-add.png \
    ../TeamManager/icons/oxygen/list-remove-user.png \
    ../TeamManager/icons/oxygen/list-remove.png \
    ../TeamManager/icons/oxygen/list-add-user.png \
    ../TeamManager/icons/oxygen/list-add-font.png \
    ../TeamManager/icons/oxygen/list-add.png \
    ../TeamManager/icons/oxygen/layer-visible-on.png \
    ../TeamManager/icons/oxygen/layer-visible-off.png \
    ../TeamManager/icons/oxygen/key-enter.png \
    ../TeamManager/icons/oxygen/journal-new.png \
    ../TeamManager/icons/oxygen/irc-voice.png \
    ../TeamManager/icons/oxygen/irc-unvoice.png \
    ../TeamManager/icons/oxygen/irc-remove-operator.png \
    ../TeamManager/icons/oxygen/irc-operator.png \
    ../TeamManager/icons/oxygen/irc-join-channel.png \
    ../TeamManager/icons/oxygen/irc-close-channel.png \
    ../TeamManager/icons/oxygen/insert-text.png \
    ../TeamManager/icons/oxygen/insert-table.png \
    ../TeamManager/icons/oxygen/insert-link.png \
    ../TeamManager/icons/oxygen/insert-image.png \
    ../TeamManager/icons/oxygen/insert-horizontal-rule.png \
    ../TeamManager/icons/oxygen/im-yahoo.png \
    ../TeamManager/icons/oxygen/im-user-offline.png \
    ../TeamManager/icons/oxygen/im-user-busy.png \
    ../TeamManager/icons/oxygen/im-user-away.png \
    ../TeamManager/icons/oxygen/im-user.png \
    ../TeamManager/icons/oxygen/im-twitter.png \
    ../TeamManager/icons/oxygen/im-skype.png \
    ../TeamManager/icons/oxygen/im-qq.png \
    ../TeamManager/icons/oxygen/im-msn.png \
    ../TeamManager/icons/oxygen/im-kick-user.png \
    ../TeamManager/icons/oxygen/im-jabber.png \
    ../TeamManager/icons/oxygen/im-invisible-user.png \
    ../TeamManager/icons/oxygen/im-identi.ca.png \
    ../TeamManager/icons/oxygen/im-icq.png \
    ../TeamManager/icons/oxygen/im-google-talk.png \
    ../TeamManager/icons/oxygen/im-google.png \
    ../TeamManager/icons/oxygen/im-gadugadu.png \
    ../TeamManager/icons/oxygen/im-facebook.png \
    ../TeamManager/icons/oxygen/im-ban-user.png \
    ../TeamManager/icons/oxygen/im-ban-kick-user.png \
    ../TeamManager/icons/oxygen/im-aim.png \
    ../TeamManager/icons/oxygen/help-hint.png \
    ../TeamManager/icons/oxygen/help-feedback.png \
    ../TeamManager/icons/oxygen/help-donate.png \
    ../TeamManager/icons/oxygen/help-contextual.png \
    ../TeamManager/icons/oxygen/help-contents.png \
    ../TeamManager/icons/oxygen/help-about.png \
    ../TeamManager/icons/oxygen/go-up-search.png \
    ../TeamManager/icons/oxygen/go-up.png \
    ../TeamManager/icons/oxygen/go-top.png \
    ../TeamManager/icons/oxygen/go-previous-view-page.png \
    ../TeamManager/icons/oxygen/go-previous-view.png \
    ../TeamManager/icons/oxygen/go-previous-use.png \
    ../TeamManager/icons/oxygen/go-previous-context.png \
    ../TeamManager/icons/oxygen/go-previous.png \
    ../TeamManager/icons/oxygen/go-next-view-page.png \
    ../TeamManager/icons/oxygen/go-next-view.png \
    ../TeamManager/icons/oxygen/go-next-use.png \
    ../TeamManager/icons/oxygen/go-next-context.png \
    ../TeamManager/icons/oxygen/go-next.png \
    ../TeamManager/icons/oxygen/go-last-view-page.png \
    ../TeamManager/icons/oxygen/go-last-view.png \
    ../TeamManager/icons/oxygen/go-last.png \
    ../TeamManager/icons/oxygen/go-jump-today.png \
    ../TeamManager/icons/oxygen/go-jump-locationbar.png \
    ../TeamManager/icons/oxygen/go-jump-definition.png \
    ../TeamManager/icons/oxygen/go-jump-declaration.png \
    ../TeamManager/icons/oxygen/go-jump.png \
    ../TeamManager/icons/oxygen/go-home.png \
    ../TeamManager/icons/oxygen/go-first-view-page.png \
    ../TeamManager/icons/oxygen/go-first-view.png \
    ../TeamManager/icons/oxygen/go-first.png \
    ../TeamManager/icons/oxygen/go-down-search.png \
    ../TeamManager/icons/oxygen/go-down.png \
    ../TeamManager/icons/oxygen/go-bottom.png \
    ../TeamManager/icons/oxygen/get-hot-new-stuff.png \
    ../TeamManager/icons/oxygen/games-solve.png \
    ../TeamManager/icons/oxygen/games-hint.png \
    ../TeamManager/icons/oxygen/games-highscores.png \
    ../TeamManager/icons/oxygen/games-endturn.png \
    ../TeamManager/icons/oxygen/games-difficult.png \
    ../TeamManager/icons/oxygen/games-config-tiles.png \
    ../TeamManager/icons/oxygen/games-config-theme.png \
    ../TeamManager/icons/oxygen/games-config-options.png \
    ../TeamManager/icons/oxygen/games-config-custom.png \
    ../TeamManager/icons/oxygen/games-config-board.png \
    ../TeamManager/icons/oxygen/games-config-background.png \
    ../TeamManager/icons/oxygen/games-achievements.png \
    ../TeamManager/icons/oxygen/formula.png \
    ../TeamManager/icons/oxygen/format-text-underline.png \
    ../TeamManager/icons/oxygen/format-text-superscript.png \
    ../TeamManager/icons/oxygen/format-text-subscript.png \
    ../TeamManager/icons/oxygen/format-text-strikethrough.png \
    ../TeamManager/icons/oxygen/format-text-italic.png \
    ../TeamManager/icons/oxygen/format-text-direction-rtl.png \
    ../TeamManager/icons/oxygen/format-text-direction-ltr.png \
    ../TeamManager/icons/oxygen/format-text-color.png \
    ../TeamManager/icons/oxygen/format-text-bold.png \
    ../TeamManager/icons/oxygen/format-stroke-color.png \
    ../TeamManager/icons/oxygen/format-remove-node.png \
    ../TeamManager/icons/oxygen/format-list-unordered.png \
    ../TeamManager/icons/oxygen/format-list-ordered.png \
    ../TeamManager/icons/oxygen/format-line-spacing-triple.png \
    ../TeamManager/icons/oxygen/format-line-spacing-normal.png \
    ../TeamManager/icons/oxygen/format-line-spacing-double.png \
    ../TeamManager/icons/oxygen/format-justify-right.png \
    ../TeamManager/icons/oxygen/format-justify-left.png \
    ../TeamManager/icons/oxygen/format-justify-fill.png \
    ../TeamManager/icons/oxygen/format-justify-center.png \
    ../TeamManager/icons/oxygen/format-join-node.png \
    ../TeamManager/icons/oxygen/format-indent-more.png \
    ../TeamManager/icons/oxygen/format-indent-less.png \
    ../TeamManager/icons/oxygen/format-font-size-more.png \
    ../TeamManager/icons/oxygen/format-font-size-less.png \
    ../TeamManager/icons/oxygen/format-fill-color.png \
    ../TeamManager/icons/oxygen/format-disconnect-node.png \
    ../TeamManager/icons/oxygen/format-connect-node.png \
    ../TeamManager/icons/oxygen/format-break-node.png \
    ../TeamManager/icons/oxygen/format-add-node.png \
    ../TeamManager/icons/oxygen/fork.png \
    ../TeamManager/icons/oxygen/folder-sync.png \
    ../TeamManager/icons/oxygen/folder-new.png \
    ../TeamManager/icons/oxygen/flag-yellow.png \
    ../TeamManager/icons/oxygen/flag-red.png \
    ../TeamManager/icons/oxygen/flag-green.png \
    ../TeamManager/icons/oxygen/flag-blue.png \
    ../TeamManager/icons/oxygen/flag-black.png \
    ../TeamManager/icons/oxygen/flag.png \
    ../TeamManager/icons/oxygen/fill-color.png \
    ../TeamManager/icons/oxygen/fileview-preview.png \
    ../TeamManager/icons/oxygen/feed-subscribe.png \
    ../TeamManager/icons/oxygen/edit-undo.png \
    ../TeamManager/icons/oxygen/edit-text-frame-update.png \
    ../TeamManager/icons/oxygen/edit-table-insert-row-below.png \
    ../TeamManager/icons/oxygen/edit-table-insert-row-above.png \
    ../TeamManager/icons/oxygen/edit-table-insert-column-right.png \
    ../TeamManager/icons/oxygen/edit-table-insert-column-left.png \
    ../TeamManager/icons/oxygen/edit-table-delete-row.png \
    ../TeamManager/icons/oxygen/edit-table-delete-column.png \
    ../TeamManager/icons/oxygen/edit-table-cell-split.png \
    ../TeamManager/icons/oxygen/edit-table-cell-merge.png \
    ../TeamManager/icons/oxygen/edit-select-all.png \
    ../TeamManager/icons/oxygen/edit-select.png \
    ../TeamManager/icons/oxygen/edit-rename.png \
    ../TeamManager/icons/oxygen/edit-redo.png \
    ../TeamManager/icons/oxygen/edit-paste.png \
    ../TeamManager/icons/oxygen/edit-node.png \
    ../TeamManager/icons/oxygen/edit-image-face-show.png \
    ../TeamManager/icons/oxygen/edit-image-face-recognize.png \
    ../TeamManager/icons/oxygen/edit-image-face-detect.png \
    ../TeamManager/icons/oxygen/edit-image-face-add.png \
    ../TeamManager/icons/oxygen/edit-guides.png \
    ../TeamManager/icons/oxygen/edit-find-user.png \
    ../TeamManager/icons/oxygen/edit-find-replace.png \
    ../TeamManager/icons/oxygen/edit-find-project.png \
    ../TeamManager/icons/oxygen/edit-find-mail.png \
    ../TeamManager/icons/oxygen/edit-find.png \
    ../TeamManager/icons/oxygen/edit-delete-shred.png \
    ../TeamManager/icons/oxygen/edit-delete.png \
    ../TeamManager/icons/oxygen/edit-cut.png \
    ../TeamManager/icons/oxygen/edit-copy.png \
    ../TeamManager/icons/oxygen/edit-clear-locationbar-rtl.png \
    ../TeamManager/icons/oxygen/edit-clear-locationbar-ltr.png \
    ../TeamManager/icons/oxygen/edit-clear-list.png \
    ../TeamManager/icons/oxygen/edit-clear-history.png \
    ../TeamManager/icons/oxygen/edit-clear.png \
    ../TeamManager/icons/oxygen/edit-bomb.png \
    ../TeamManager/icons/oxygen/draw-triangle4.png \
    ../TeamManager/icons/oxygen/draw-triangle3.png \
    ../TeamManager/icons/oxygen/draw-triangle2.png \
    ../TeamManager/icons/oxygen/draw-triangle1.png \
    ../TeamManager/icons/oxygen/draw-triangle.png \
    ../TeamManager/icons/oxygen/draw-text.png \
    ../TeamManager/icons/oxygen/draw-star.png \
    ../TeamManager/icons/oxygen/draw-square-inverted-corners.png \
    ../TeamManager/icons/oxygen/draw-spiral.png \
    ../TeamManager/icons/oxygen/draw-rectangle.png \
    ../TeamManager/icons/oxygen/draw-polyline.png \
    ../TeamManager/icons/oxygen/draw-polygon.png \
    ../TeamManager/icons/oxygen/draw-path.png \
    ../TeamManager/icons/oxygen/draw-halfcircle4.png \
    ../TeamManager/icons/oxygen/draw-halfcircle3.png \
    ../TeamManager/icons/oxygen/draw-halfcircle2.png \
    ../TeamManager/icons/oxygen/draw-halfcircle1.png \
    ../TeamManager/icons/oxygen/draw-freehand.png \
    ../TeamManager/icons/oxygen/draw-eraser.png \
    ../TeamManager/icons/oxygen/draw-ellipse.png \
    ../TeamManager/icons/oxygen/draw-donut.png \
    ../TeamManager/icons/oxygen/draw-cross.png \
    ../TeamManager/icons/oxygen/draw-circle.png \
    ../TeamManager/icons/oxygen/draw-brush.png \
    ../TeamManager/icons/oxygen/draw-bezier-curves.png \
    ../TeamManager/icons/oxygen/draw-arrow-up.png \
    ../TeamManager/icons/oxygen/draw-arrow-forward.png \
    ../TeamManager/icons/oxygen/draw-arrow-down.png \
    ../TeamManager/icons/oxygen/draw-arrow-back.png \
    ../TeamManager/icons/oxygen/download-later.png \
    ../TeamManager/icons/oxygen/download.png \
    ../TeamManager/icons/oxygen/document-sign.png \
    ../TeamManager/icons/oxygen/document-save-as.png \
    ../TeamManager/icons/oxygen/document-save-all.png \
    ../TeamManager/icons/oxygen/document-save.png \
    ../TeamManager/icons/oxygen/document-revert.png \
    ../TeamManager/icons/oxygen/document-properties.png \
    ../TeamManager/icons/oxygen/document-print-preview.png \
    ../TeamManager/icons/oxygen/document-print-frame.png \
    ../TeamManager/icons/oxygen/document-print-direct.png \
    ../TeamManager/icons/oxygen/document-print.png \
    ../TeamManager/icons/oxygen/document-preview-archive.png \
    ../TeamManager/icons/oxygen/document-preview.png \
    ../TeamManager/icons/oxygen/document-open-remote.png \
    ../TeamManager/icons/oxygen/document-open-recent.png \
    ../TeamManager/icons/oxygen/document-open-folder.png \
    ../TeamManager/icons/oxygen/document-open.png \
    ../TeamManager/icons/oxygen/document-new.png \
    ../TeamManager/icons/oxygen/document-import.png \
    ../TeamManager/icons/oxygen/document-export-table.png \
    ../TeamManager/icons/oxygen/document-export.png \
    ../TeamManager/icons/oxygen/document-encrypted.png \
    ../TeamManager/icons/oxygen/document-encrypt.png \
    ../TeamManager/icons/oxygen/document-edit-verify.png \
    ../TeamManager/icons/oxygen/document-edit-sign-encrypt.png \
    ../TeamManager/icons/oxygen/document-edit-sign.png \
    ../TeamManager/icons/oxygen/document-edit-encrypt.png \
    ../TeamManager/icons/oxygen/document-edit-decrypt-verify.png \
    ../TeamManager/icons/oxygen/document-edit-decrypt.png \
    ../TeamManager/icons/oxygen/document-edit.png \
    ../TeamManager/icons/oxygen/document-decrypt.png \
    ../TeamManager/icons/oxygen/document-close.png \
    ../TeamManager/icons/oxygen/documentation.png \
    ../TeamManager/icons/oxygen/distribute-vertical-y.png \
    ../TeamManager/icons/oxygen/distribute-vertical-top.png \
    ../TeamManager/icons/oxygen/distribute-vertical-page.png \
    ../TeamManager/icons/oxygen/distribute-vertical-margin.png \
    ../TeamManager/icons/oxygen/distribute-vertical-equal.png \
    ../TeamManager/icons/oxygen/distribute-vertical-center.png \
    ../TeamManager/icons/oxygen/distribute-vertical-bottom.png \
    ../TeamManager/icons/oxygen/distribute-horizontal-x.png \
    ../TeamManager/icons/oxygen/distribute-horizontal-right.png \
    ../TeamManager/icons/oxygen/distribute-horizontal-page.png \
    ../TeamManager/icons/oxygen/distribute-horizontal-margin.png \
    ../TeamManager/icons/oxygen/distribute-horizontal-left.png \
    ../TeamManager/icons/oxygen/distribute-horizontal-equal.png \
    ../TeamManager/icons/oxygen/distribute-horizontal-center.png \
    ../TeamManager/icons/oxygen/dialog-ok-apply.png \
    ../TeamManager/icons/oxygen/dialog-ok.png \
    ../TeamManager/icons/oxygen/dialog-close.png \
    ../TeamManager/icons/oxygen/dialog-cancel.png \
    ../TeamManager/icons/oxygen/debug-step-over.png \
    ../TeamManager/icons/oxygen/debug-step-out.png \
    ../TeamManager/icons/oxygen/debug-step-into-instruction.png \
    ../TeamManager/icons/oxygen/debug-step-into.png \
    ../TeamManager/icons/oxygen/debug-step-instruction.png \
    ../TeamManager/icons/oxygen/debug-run-cursor.png \
    ../TeamManager/icons/oxygen/debug-run.png \
    ../TeamManager/icons/oxygen/debug-execute-to-cursor.png \
    ../TeamManager/icons/oxygen/debug-execute-from-cursor.png \
    ../TeamManager/icons/oxygen/dashboard-show.png \
    ../TeamManager/icons/oxygen/contact-new.png \
    ../TeamManager/icons/oxygen/configure-toolbars.png \
    ../TeamManager/icons/oxygen/configure-shortcuts.png \
    ../TeamManager/icons/oxygen/configure.png \
    ../TeamManager/icons/oxygen/color-picker-white.png \
    ../TeamManager/icons/oxygen/color-picker-grey.png \
    ../TeamManager/icons/oxygen/color-picker-black.png \
    ../TeamManager/icons/oxygen/color-picker.png \
    ../TeamManager/icons/oxygen/code-variable.png \
    ../TeamManager/icons/oxygen/code-typedef.png \
    ../TeamManager/icons/oxygen/code-function.png \
    ../TeamManager/icons/oxygen/code-context.png \
    ../TeamManager/icons/oxygen/code-class.png \
    ../TeamManager/icons/oxygen/code-block.png \
    ../TeamManager/icons/oxygen/chronometer.png \
    ../TeamManager/icons/oxygen/checkbox.png \
    ../TeamManager/icons/oxygen/character-set.png \
    ../TeamManager/icons/oxygen/call-stop.png \
    ../TeamManager/icons/oxygen/call-start.png \
    ../TeamManager/icons/oxygen/bookmark-toolbar.png \
    ../TeamManager/icons/oxygen/bookmarks-organize.png \
    ../TeamManager/icons/oxygen/bookmark-new-list.png \
    ../TeamManager/icons/oxygen/bookmark-new.png \
    ../TeamManager/icons/oxygen/arrow-up-double.png \
    ../TeamManager/icons/oxygen/arrow-up.png \
    ../TeamManager/icons/oxygen/arrow-right-double.png \
    ../TeamManager/icons/oxygen/arrow-right.png \
    ../TeamManager/icons/oxygen/arrow-left-double.png \
    ../TeamManager/icons/oxygen/arrow-left.png \
    ../TeamManager/icons/oxygen/arrow-down-double.png \
    ../TeamManager/icons/oxygen/arrow-down.png \
    ../TeamManager/icons/oxygen/archive-remove.png \
    ../TeamManager/icons/oxygen/archive-insert-directory.png \
    ../TeamManager/icons/oxygen/archive-insert.png \
    ../TeamManager/icons/oxygen/archive-extract.png \
    ../TeamManager/icons/oxygen/appointment-new.png \
    ../TeamManager/icons/oxygen/application-exit.png \
    ../TeamManager/icons/oxygen/align-vertical-top.png \
    ../TeamManager/icons/oxygen/align-vertical-center.png \
    ../TeamManager/icons/oxygen/align-vertical-bottom.png \
    ../TeamManager/icons/oxygen/align-horizontal-top-out.png \
    ../TeamManager/icons/oxygen/align-horizontal-right-out.png \
    ../TeamManager/icons/oxygen/align-horizontal-right.png \
    ../TeamManager/icons/oxygen/align-horizontal-left-out.png \
    ../TeamManager/icons/oxygen/align-horizontal-left.png \
    ../TeamManager/icons/oxygen/align-horizontal-center.png \
    ../TeamManager/icons/oxygen/align-horizontal-bottom-out.png \
    ../TeamManager/icons/oxygen/address-book-new.png

FORMS += \
    ../TeamManager/watchfieldgraphics.ui \
    ../TeamManager/mainwindow.ui \
    ../TeamManager/plot-manager/scatterplotwidget.ui \
    ../TeamManager/plot-manager/plotwidget.ui \
    ../TeamManager/plot-manager/plotmanagerwidget.ui

RESOURCES += \
    ../TeamManager/icons.qrc

